### ISSUE TITLE
Add Angular example 

### ISSUE THREAD

**Issue by joshribakoff** [rx-store/rx-store#6]
Maybe helpful:

https://github.com/ngrx/platform/blob/master/modules/store/src/store_module.ts
https://ngrx.io/guide/store/install

**Comment by gennadypolakov** [comment]
@joshribakoff 
Hi, can I work on this?

**Comment by joshribakoff** [comment]
@gennadypolakov absolute! Thanks :) let me know what I can do to help support you, or feel free to have at :)
